### ISSUE TITLE
Msktutil -s to create new service principle?

### ISSUE THREAD

**Issue by Lippseric** [msktutil/msktutil#111]
Hello,

I'm trying to figure out how to use msktutil to create new service principles in AD from a linux machine. currently I'm using a windows machine to do this with setspn, and I'm having trouble transferring the commands to msktutil.

say this command is what I'm using in setspn:
`
setspn -U -A service/hostyboy.domain.com domain1\registeredAccount`

how would I translate this to msktutil -s ?

I've tried:
`msktutil -s registeredAccount/hostyboy.domain.com ` 
but this doesn't specify the service name or the domain?

**Comment by sckobras** [comment]
Do you want to write out a new keytab in the process as well, or do you just want to modify the object in AD? For the former,

`# msktutil update --dont-change-password -s service/hostyboy.domain.com --use-service-account --account-name registeredAccount`

should get you close, provided that access is allowed with your current set of credentials. As for the latter, msktutil doesn't currently cater for this use case. There's always the hard way, of course, like

`# printf 'dn: %s\nchangetype: modify\nadd: servicePrincipalName\nservicePrincipalName: %s\n\n' "$dn"  "$spn" | ldapmodify "$domain"`

You can use `ldapsearch -h "$domain" -b "$basedn" "(sAMAccountName=$accountname)" dn` to obtain the account's dn for use with ldapmodify above.

**Comment by Lippseric** [comment]
Thank you so much! this is exactly what I was looking for and it saved me so much time. The alternative was setting up a windows VM and passing my commands through it, which I wasn't looking forward to. :P

**Comment by Lippseric** [comment]
Follow-up question -- how would I delete the same service principle? I'm working in a VM environment and we are filling the AD with quite a lot of garbage once the VMs are deleted.
