### ISSUE TITLE
Rename configure.in to configure.ac

### ISSUE THREAD

**Issue by michael-o** [msktutil/msktutil#121]
I receive the following warning:

    aclocal-1.15: warning: autoconf input should be named 'configure.ac', not 'configure.in'

I think we should comply with that.

**Comment by Polynomial-C** [comment]
See [Writing configure.ac](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Writing-Autoconf-Input.html#Writing-Autoconf-Input) from the GNU autoconf documentation:
```
Previous versions of Autoconf promoted the name configure.in, which is somewhat ambiguous (the 
tool needed to process this file is not described by its extension), and introduces a slight confusion 
with config.h.in and so on (for which ‘.in’ means “to be processed by configure”). Using configure.ac is 
now preferred.
```

See also this commit in autoconf git repo: [deprecate 'configure.in' as autoconf input](http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=commit;h=560f16b52d3d3db1536d9ca5b863ce9b1a5c9e35)
