### ISSUE TITLE
Cannot find input file: 

### ISSUE THREAD

**Issue by Dylan-MSFT** [msktutil/msktutil#123]

**Comment by Dylan-MSFT** [comment]
With the latest checkin, ./configure on a fresh install fails with the message "Cannot find input file: 'config.h.in'".

**Comment by dkobras** [comment]
Running `autoconf` is no longer sufficient (by design). You also need to run `autoheader` beforehand. That's what running `./autogen.sh` will do automatically.

**Comment by Dylan-MSFT** [comment]
Ah. Thanks for the clarification

**Comment by oflebbe** [comment]
I will add a short paragraph to the README file
