### ISSUE TITLE
Alternative creation of salt value via krb5_get_etype_salt_s2k()

### ISSUE THREAD

**Issue by mproehl** [msktutil/msktutil#135]
According to http://mailman.mit.edu/pipermail/krbdev/2018-September/013007.html there will be an new way to retrieve the salt value from AD in MIT 1.17 or later.

**Comment by dkobras** [comment]
See also #156

**Comment by michael-o** [comment]
What about Heimdal? How do you want to handle that? Configure time?

**Comment by dkobras** [comment]
Yes, for Heimdal, we'll have to stick with the current heuristics.

**Comment by michael-o** [comment]
So, there will be a compile time switch MIT Kerberos => 1..17 or (below and Heimdal).

**Comment by dkobras** [comment]
Exactly, that's what I have in mind.

**Comment by michael-o** [comment]
This makes sense. Test for the new function and have a `HAVE_` macro and do new magic.
