### ISSUE TITLE
README is incomplete

### ISSUE THREAD

**Issue by uli42** [msktutil/msktutil#137]
README has some history at the end. I think there are some people missing, e.g. dkobras. Also some of the provided email addresses need updates.

**Comment by oflebbe** [comment]
Hi @uli42, I just like to explore the possibilty of you providing a pull request :-) You may add @dkobras as a reviewer.

**Comment by dkobras** [comment]
Heh, look at it this way--at least I'm not history, yet! ;-)
Seriously, though, thanks for the report. Updating the README, and the copyright info in particular is something we'd typically do right before a new release. At this point, mail addresses will get updated as well. I've added this issue to the next milestone, so we keep it in mind before v1.2 hits the road.

**Comment by uli42** [comment]
Well, YOUR email is still wrong in that commit.

**Comment by dkobras** [comment]
@uli42 Hi! 

> Well, YOUR email is still wrong in that commit.

Which one are you referring to?

```
          (C) 2013-2017 Daniel Kobras <d.kobras at science-computing.de>
 ```

and

```
         (C) 2018-2022 Daniel Kobras <kobras at puzzle-itc.de>
```

The first one is outdated, but there's also a timeframe given, and the attribution remains accurate. Hence, both look correct to me.

**Comment by uli42** [comment]
If the email is outdated there's no point in keeping it, I'd say. At least
the person behind both addresses is the same and the timeframe is not
overlapping but continuous. YMMV.
