### ISSUE TITLE
[SOLVED] Error: krb5_get_default_realm failed

### ISSUE THREAD

**Issue by manjotsc** [msktutil/msktutil#143]
I am getting this error **"Error: krb5_get_default_realm failed"** when running : **msktutil -N -c -b 'CN=Linux' -s POP-OS/pop-os.*******.net -k popkey.keytab --computer-name POP-OS --upn POP-OS$ --server server.*******.net --user-creds-only**

following this guide: https://support.system76.com/articles/active-directory-client/

![Screenshot from 2020-01-28 15-31-26](https://user-images.githubusercontent.com/51430971/73303497-9c5e5c00-41e4-11ea-93d6-9d5db8af5ff9.png)

**Comment by dkobras** [comment]
Hi! Sounds like there's something wrong with the `default_realm` entry in `/etc/krb5.conf`. What does the `[libdefaults]` section in this file look like? As a quick workaround, you can also use the `--realm` option to pass the name of your Kerberos realm directly to `msktutil`.

**Comment by manjotsc** [comment]
![Screenshot from 2020-01-28 11-47-59](https://user-images.githubusercontent.com/51430971/73308618-adac6600-41ee-11ea-884b-0bed1df3830a.png)

**Comment by manjotsc** [comment]
![Screenshot from 2020-01-28 11-47-59](https://user-images.githubusercontent.com/51430971/73350402-f00b8c80-425a-11ea-801c-99297a6b8a65.png)

**Comment by manjotsc** [comment]
worked,  there was empty **default_realm = my.domain**, hidden, I never noticed unit I try scroll it up.

**Comment by dkobras** [comment]
Thanks for the feedback! Glad to hear that now it's working for you.
