### ISSUE TITLE
Thank you for this software

### ISSUE THREAD

**Issue by nktl** [msktutil/msktutil#144]
Just wanted to say thank you for this fantastic piece of software.

It is the best solution for maintaining accounts, SPNs and keytabs in AD environment from Linux - and we have tried them all.

You are doing Lord's work - please keep it up!

**Comment by dkobras** [comment]
@nktl Thanks for the comment--made my day. ;-)

**Comment by michael-o** [comment]
I may haven't expressed by gratitude too. This tool is a lifesaver on HP-UX. Extremely crucial for us.

**Comment by oflebbe** [comment]
@nktl Thanks !
