### ISSUE TITLE
Don't install to $PREFIX/sbin

### ISSUE THREAD

**Issue by michael-o** [msktutil/msktutil#146]
I think it is a common misconception that this tool needs to be installed to `sbin`. This tool isn't restricted to root only. I may be well used by users or daemon accounts w/o root privs at all. It is by default not in `PATH` at least ont here on FreeBSD and HP-UX which annoys users. If the machine keytab is tried to modified w/o root privs, it will fail anyway.
We should simply install to `$PREFIX/bin`. Done.

**Comment by dkobras** [comment]
I'd be fine with putting it in `$PREFIX/bin`. However, if we choose to move the binary, we should keep backward compatibility in mind and at least leave a symlink at the old location, so scripts that hard-code `$PREFIX/bin/msktutil` won't break after an upgrade.

**Comment by michael-o** [comment]
Sounds reasonable!
