### ISSUE TITLE
Autoupdate keytab timeout

### ISSUE THREAD

**Issue by Abyss777** [msktutil/msktutil#149]
Hello
I'm using next line to auto update keytab every night
```
/usr/sbin/msktutil  --auto-update --use-service-account --service HTTP/mail.rg.local --keytab /opt/zimbra/data/mailboxd/spnego/jetty.keytab --account-name mail-http --enctypes 0x1f --no-pac --server dc02.rg.local
```

Also I'm using https://github.com/jephthai/OpenPasswordFilter to validate users passwords.
The manual process of changing/setting password takes about 5-10 seconds even if user is not in group to validate. (I believe checking group takes too long)
But still manual password changing went successful.

_msktutil_ fails in 1 second with
```Error: Unable to set machine password for mail-http: (3) Authentication error
Error: set_password failed
Hint: Does your password policy allow to change mail-http's password?
      For example, there could be a "Minimum password age" policy preventing
      passwords from being changed too frequently. If so, you can reset the
      password instead of changing it using the --user-creds-only option.
      Be aware that you need a ticket of a user with administrative privileges
      for that.
```
I believe _msktutil_ fails earlier than password changing really happen.

If I disable OPF on a server autoupdate is OK.

Is there a way to tune timeout of setting password via _msktutil_?

**Comment by dkobras** [comment]
We don't impose a timeout on password changes--something else must be at fault here. The `krb5` error message should give a hint on what's going on here: Can you please re-run the test and supply option `--verbose` to your `msktutil` command-line? Also, to closely mimick a password change with `msktuil`, you can try to run `kpasswd <username>` on the same machine, and set a random password of 63 ASCII characters in the range between `0x21` and `0x7e`. I'd expect this command to fail in your environment, but hopefully provide a useful error message.

**Comment by michael-o** [comment]
One can also set `KRB5_TRACE=out`.

**Comment by dkobras** [comment]
Unfortunately, we cannot futher debug this issue without the requested info. Please feel free to re-open with the additional data.
