### ISSUE TITLE
please apply PR#151 (permit specifying candidate SASL mechanisms for the LDAP bind)

### ISSUE THREAD

**Issue by qralston** [msktutil/msktutil#152]
PR #151 changes the default candidate SASL mechanisms string from `GSSAPI` to `GSS-SPNEGO GSSAPI`, and provides a new `--sasl-mechanisms` option to permit overriding the SASL mechanisms string.

Generally speaking, Microsoft seems to prefer GSS-SPNEGO over GSSAPI nowadays: using GSSAPI instead of GSS-SPNEGO will throw errors in the Windows Event Log. So it makes sense to update the default candidate SASL mechanisms string. If GSS-SPNEGO isn't available on both the client and the server, GSSAPI will be used instead, the same as now.

For more information, see the PR.

Thanks for all of the work on msktutil—out of all of the various utilities that can join a Linux host to AD, we've found msktutil to be both the most reliable and the most feature-rich.

**Comment by dkobras** [comment]
PR #151 has been merged. Thanks for your contribution!
