### ISSUE TITLE
SPN host/shortname not created

### ISSUE THREAD

**Issue by mproehl** [msktutil/msktutil#153]
Running `msktutil create` creates

(a) A keytab with entries for host/FQDN and host/shortname. E.g.:

    root@lx02.ads:~# msktutil create --enctypes 0x10
    root@lx02.ads:~# klist -ke
    Keytab name: FILE:/etc/krb5.keytab
    KVNO Principal
    ---- --------------------------------------------------------------------------
       2 lx02$@ADS.EXAMPLE.COM (aes256-cts-hmac-sha1-96) 
       2 LX02$@ADS.EXAMPLE.COM (aes256-cts-hmac-sha1-96) 
       2 host/lx02@ADS.EXAMPLE.COM (aes256-cts-hmac-sha1-96) 
       2 host/lx02.ads.example.com@ADS.EXAMPLE.COM (aes256-cts-hmac-sha1-96) 
    root@lx02.ads:~# 

(b)  SPNs in the corresponding AD object:

      servicePrincipalName: host/lx02.ads.example.com

The servicePrincipalName: host/lx02 is missing and that should be fixed.

**Comment by mproehl** [comment]
PR created

**Comment by michael-o** [comment]
This perfectly makes sense and this is what I have noticed to be missing!
