### ISSUE TITLE
Creating service account entries with UPN yields invalid keytab

### ISSUE THREAD

**Issue by dkobras** [msktutil/msktutil#156]
`msktutil create --use-service-account --service HTTP/foo --account-name foo --upn HTTP/foo --keytab /tmp/foo.keytab` creates a keytab file with invalid entries for both SPNs and UPNs. Presumably the salt is guessed incorrectly in this case.

**Comment by dkobras** [comment]
Further testing reveals that indeed AD uses a salt of `REALMfoo` (ie. derived from the sAMAccountName) for the keys created with the above command, whereas `msktutil` (incorrectly) guesses the salt as `REALMHTTPfoo` (ie. derived from the UPN).

**Comment by dkobras** [comment]
Reason: UPN is only added once the keys have already been created. Hence, the salt is not changed to include the UPN.
Workaround: Rotating the keys after updating the UPN makes sure that `msktutil` heuristics guess the correct salt.

**Comment by dkobras** [comment]
With MIT Kerberos, `ktutil add_entry` nowadays support a flag `-f` that fetches information about the salt from the KDC. If we're able to use the same interface, this should supersede our internal heuristics, and always provide us with a proper salt.

**Comment by dkobras** [comment]
[`krb5_get_etype_info()`](https://web.mit.edu/kerberos/krb5-devel/doc/appdev/refs/api/krb5_get_etype_info.html) (available since v1.17) provides the necessary info.

**Comment by michael-o** [comment]
Major changes in 1.17 (2019-01-08). 2,5 years back. Question is do we make this now mandatory, or query for this function and configure time and use a `HAVE_...`? If not available, fall back to old approach?

**Comment by dkobras** [comment]
We'll have to keep the current code anyway as a fallback for Heimdal, so we can just as well use it for older MIT as well, and just use the new function based on a configure check.

**Comment by dkobras** [comment]
Fixed in #187
