### ISSUE TITLE
Fix compiler warnings on FreeBSD clang version 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2)

### ISSUE THREAD

**Issue by michael-o** [msktutil/msktutil#161]
I see:
```
c++ -I.  -I/usr/local/include -g -O2 -Wall -Wextra -Wno-write-strings -c msktname.cpp -o msktname.o
msktname.cpp:148:9: warning: ISO C++ requires field designators to be specified in declaration
      order; field 'ai_addr' will be initialized after field 'ai_canonname'
      [-Wreorder-init-list]
        .ai_canonname = NULL,
        ^~~~~~~~~~~~~~~~~~~~
msktname.cpp:147:20: note: previous initialization for field 'ai_addr' is here
        .ai_addr = NULL,
                   ^~~~
```

**Comment by oflebbe** [comment]
This is one of the reasons we should move away from C++.

This compiler diagnostic is a red hering : Looks like the order of members within "struct addrinfo" is not the same on each platform. The Warning does make sense for C++, but not for using C as a C++ compiler.
We could reverse initialization of ai_cannonname and ai_addr to satisfy FreeBSD, only to break Linux .

I would rather propose to rewrite this part as C

**Comment by oflebbe** [comment]
Checking with MacOSX: The order of ai_addr and ai_canonname are reversed with respect to Linux glibc.
Seems only FreeBSD's clang is picky about the ordering within C structs .

**Comment by oflebbe** [comment]
Checking with the POSIX Standard document. They don't specify ordering / layout of struct addrinfo.
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netdb.h.html

**Comment by oflebbe** [comment]
Oh wow, with g++ this would not even a warning, it would be an error !

**Comment by oflebbe** [comment]
Indeed ! MacOSX with gcc from Homebrew does not compile msktutil . We need to fix this somehow.

```
msktname.cpp: In member function 'bool DnsSrvHost::validate(bool, std::string)':
msktname.cpp:150:5: warning: missing initializer for member 'addrinfo::ai_canonname' [-Wmissing-field-initializers]
  150 |     };
      |     ^
msktname.cpp:150:5: warning: missing initializer for member 'addrinfo::ai_next' [-Wmissing-field-initializers]
msktname.cpp:150:5: error: designator order for field 'addrinfo::ai_canonname' does not match declaration order in 'addrinfo'
make: *** [msktname.o] Error 1

```
