### ISSUE TITLE
Vector of enc types has wrong types

### ISSUE THREAD

**Issue by michael-o** [msktutil/msktutil#170]
`add_principal_keytab()` has `std::vector<uint32_t> enc_types`, but MIT Kerberos defines https://github.com/krb5/krb5/blob/9241e2e2ee83b11f5f585676b1f2283670dd0178/src/include/krb5/krb5.hin#L136 and https://github.com/krb5/krb5/blob/9241e2e2ee83b11f5f585676b1f2283670dd0178/src/include/krb5/krb5.hin#L176.

Heimdal does https://github.com/heimdal/heimdal/blob/22b8c3d44821fec1e564d92f3a5608cef6b92f51/lib/krb5/krb5.h#L104 and https://github.com/heimdal/heimdal/blob/22b8c3d44821fec1e564d92f3a5608cef6b92f51/lib/asn1/krb5.asn1#L253.

We should change this to `int32_t` too.

**Comment by oflebbe** [comment]
Thanks for mentioning
