### ISSUE TITLE
Is this an extraneous LDAP call?

### ISSUE THREAD

**Issue by miketheitguy** [msktutil/msktutil#180]
https://github.com/msktutil/msktutil/blob/57164e3be5e08ff547addbe37c443d05ca14a97b/msktpass.cpp#L169

I was reviewing some network traces of msktutil yesterday and noticed LDAP calls that seemed to be out of place. When we took a deep dive into the code, we found this. I can't see where the output of old_pwdlastset is used or set? So is this just an extraneous network call?

**Comment by dkobras** [comment]
Indeed, good catch! The info used to be handed down to `wait_on_pwchange()`. But commit `bb40b477bb5fda9196c09507f2e87377fe48a218` removed the logic to wait for password replication to proceed, so `old_pwdLastSet` became unused. I'll clean this up.

**Comment by dkobras** [comment]
Fixed in PR #181, which has just been merged.
