### ISSUE TITLE
Push version 1.2

### ISSUE THREAD

**Issue by michael-o** [msktutil/msktutil#182]
We haven't had a release in three years. I think it is about time to push out 1.2 to the public. WDYT?

**Comment by dkobras** [comment]
I've just thought about this as well, recently, and I'm all for it. There are a few open PRs that have been pending for quite a while. How about we fix a date a few weeks down, and release anything that's made it to master by then as v1.2? Oct 1st 2021 sounds plausible to me.

**Comment by michael-o** [comment]
Agree!

**Comment by dkobras** [comment]
@mproehl would that be okay with you as well?

**Comment by mproehl** [comment]
I would agree with Oct 1st 2021 or maybe one or to weeks later...

**Comment by michael-o** [comment]
Folks, I'd like to push 1.2 in January. Can you please have a look what you see realistic in 1.2 in Jan? Otherwise we should move to 1.3.

**Comment by mproehl** [comment]
Hi Michael, I will have a look at what is realistic in the beginning of next year.

**Comment by Foorack** [comment]
Hello, just ran into https://github.com/msktutil/msktutil/pull/141 and noticed we were not running latest version, and that a newer version hasn't been released since it was merged... Would love a new release if possible. Would be greatly appreciated! :+1:

**Comment by michael-o** [comment]
Guys, a few open issues are still open. Shall we move them? I'd like to push a release until end of next week.

**Comment by dkobras** [comment]
@michael-o I've started updating docs for v1.2 locally, which also includes the README. Other than documentation, there's only #74 left. This one's assigned to you, so I'll leave it up to you whether you want to address it for v1.2 or postpone to a later release.

**Comment by michael-o** [comment]
@dkobras Thanks, I will try to take a look at #74 and #173.

**Comment by dkobras** [comment]
I've added some documentation updates for v1.2 in the draft PR #196. This is certainly not complete, yet. Feel free to add and edit.

**Comment by michael-o** [comment]
As it seems all issues are resolved for 1.2. I will perform the release on Monday. Thus, the community still have a few days to report issues if necessary.

**Comment by dkobras** [comment]
@michael-o I've added a (trivial) PR for the actual release. (Hopefully the signed tag survives. Otherwise we can still tag directly to the upstream repo.) As far as I'm concerned, feel free to merge any time.
