### ISSUE TITLE
404 in README

### ISSUE THREAD

**Issue by michael-o** [msktutil/msktutil#198]
Both https://www.pppl.gov/~dperry/ and http://download.systemimager.org/~finley/msktutil/ are dead.

**Comment by michael-o** [comment]
@dkobras Should we just drop those links?

**Comment by dkobras** [comment]
@michael-o Probably not much value in keeping those links around today. We even might drop the historic references for dates from 2010 onwards as it is documented in `git` already.

**Comment by michael-o** [comment]
Then let's drop it if it duplicates other information....
