### ISSUE TITLE
dns_lookup_kdc setting in create_fake_krb5_conf causes issue when using a trusted domain user to create computer account

### ISSUE THREAD

**Issue by daniellindgren2020** [msktutil/msktutil#208]
Short version:

If you use msktutil to create a computer account in an Active Directory domain with user credentials from a different trusted AD domain, the command fails, because dns_lookup_kdc is set to false in fake krb5.conf.

Longer version:

(Domain, host and user information anonymized for security reasons.)

We have two AD domains, DomA.domain.tld and DomB.domain.tld.
The domains are in separate forests.
DomB (one way) trusts DomA. 

DomA has a domain controller named DcA.DomA.domain.tld.
DomB has a domain controller named DcB.DomB.domain.tld.

In DomA we have a user, UserA, who has been granted permissions to create computer accounts in DomB.

We have a Linux machine, HostB (FQDN HostB.DomB.domain.tld), that we want to join to DomB, using msktutil to create the computer account and system keytab.

HostB has a krb5.conf file with settings that enables DNS lookup for realm and KDC:

    [libdefaults]
        dns_lookup_realm = true
        dns_lookup_kdc = true

We start by using a user keytab file to get a ticket for UserA (principal UserA@DOMA.DOMAIN.TLD) on HostB.

We then use msktutil to join HostB to DomB, with the credentials for UserA.

msktutil fails with this error (with --verbose):

    -- create_fake_krb5_conf: Created fake krb5.conf file: /tmp/.msktkrb5.conf-NzPlNt
    [...]
    -- finalize_exec: Authenticated using method 5
    -- LDAPConnection: Connecting to LDAP server: DcB.DomB.domain.tld
    SASL/GSS-SPNEGO authentication started
    Error: ldap_sasl_interactive_bind_s failed (Local error)
        additional info: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Cannot find KDC for realm "DOMA.DOMAIN.TLD")
    Error: ldap_connect failed

Since there was no issue finding KDC for DOMA.DOMAIN.TLD when using a user keytab file and the hosts krb5.conf, we figured that the fake krb.conf file has to differ i some way. Checking the source code we find this:

    file << "[libdefaults]\n"
         << " default_realm = " << flags->realm_name << "\n"
         << " dns_lookup_kdc = false\n"
         << " udp_preference_limit = 1\n"
         << " default_ccache_name = " << KRB5CCache::defaultName() << "\n";

We changed dns_lookup_kdc to true, rebuilt msktutil and ran the command again, this time we could successfully join HostB to DomB with UserA credentials :

    -- create_fake_krb5_conf: Created fake krb5.conf file: /tmp/.msktkrb5.conf-yEjn1J
    [...]
    -- finalize_exec: Authenticated using method 5
    -- LDAPConnection: Connecting to LDAP server: DcB.DomB.domain.tld
    SASL/GSS-SPNEGO authentication started
    SASL username: UserA@DOMA.DOMAIN.TLD
    SASL SSF: 256
    SASL data security layer installed.
    [...]
    -- ldap_create_account: Computer account not found, create one

Is there a reason that dns_lookup_kdc is set to false in the fake krb5.conf file?
Could the default be changed to true?
If not, could a command line option be added to msktutil to set it to true?

Cheers,
Daniel

**Comment by michael-o** [comment]
> (Domain, host and user information anonymized for security reasons.)

and you believe if we'd know then we could access them although they are physically not routable from the internert?

**Comment by michael-o** [comment]
Please supply all args passed to msktutil. First shot: We do discover a KDC in code, thereforce the fake krb.conf does not need to discover it again.

**Comment by daniellindgren2020** [comment]
> > (Domain, host and user information anonymized for security reasons.)
> 
> And you believe if we'd know then we could access them although they are physically not routable from the internert?

It's company policy. We could discuss that or do something more productive.

**Comment by daniellindgren2020** [comment]
> Please supply all args passed to msktutil.

./msktutil create -b "OU=Specific OU for Linux" --computer-name `hostname -s` -k /etc/krb5.keytab --dont-expire-password --enctypes 16 -s host/`hostname -s`

**Comment by michael-o** [comment]
> > > (Domain, host and user information anonymized for security reasons.)
> > 
> > 
> > And you believe if we'd know then we could access them although they are physically not routable from the internert?
> 
> It's company policy. We could discuss that or do something more productive.

Discussing company policies is the best you can do to kill time efficiently :-D

**Comment by michael-o** [comment]
Please also share your `/etc/krb5.conf`.

**Comment by daniellindgren2020** [comment]
> Please provide _full_ verbose output, obfuscate if you want to.

[root@HostB ~]# msktutil create -b "OU=Specific OU for Linux" --computer-name `hostname -s` -k /etc/krb5.keytab --dont-expire-password --enctypes 16 -s host/`hostname -s` --verbose
 -- init_password: Wiping the computer password structure
 -- generate_new_password: Generating a new, random password for the computer account
 -- generate_new_password: Characters read from /dev/urandom: 76
 -- get_dc_host: Attempting to find domain controller to use via DNS SRV record in domain DOMB.DOMAIN.TLD for procotol tcp
 -- DnsSrvQuery: Running DNS SRV query for _kerberos._tcp.dc._msdcs.DOMB.DOMAIN.TLD
 -- validate: Found DC: dcb.domb.domain.tld. Checking availability...
 -- get_dc_host: Found preferred domain controller: DCB.domb.domain.tld
 -- create_fake_krb5_conf: Created fake krb5.conf file: /tmp/.msktkrb5.conf-NzPlNt
 -- destroy_g_context: Destroying Kerberos context
 -- initialize_g_context: Creating Kerberos context
 -- finalize_exec: sAMAccountName: HostB$
 -- get_short_hostname: Determined short hostname: HostB
 -- get_short_hostname: Determined short hostname: HostB
 -- try_machine_password: Trying to authenticate HostB$ with password
 -- create_default_machine_password: Default machine password for HostB$ is HostB
 -- try_machine_password: Error: krb5_get_init_creds_keytab failed: Client not found in Kerberos database
 -- try_machine_password: Authentication with password failed
 -- try_user_creds: Checking if default ticket cache has tickets
 -- finalize_exec: Authenticated using method 5
 -- LDAPConnection: Connecting to LDAP server: DCB.domb.domain.tld
SASL/GSS-SPNEGO authentication started
Error: ldap_sasl_interactive_bind_s failed (Local error)
	additional info: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Cannot find KDC for realm "DOMA.DOMAIN.TLD")
Error: ldap_connect failed
--> Is your kerberos ticket expired? You might try re-"kinit"ing.
--> Is DNS configured correctly? You might try options "--server" and "--no-reverse-lookups".
[root@HostB ~]#

**Comment by daniellindgren2020** [comment]
> Please also share your `/etc/krb5.conf`.

[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 dns_lookup_realm = true
 dns_lookup_kdc = true
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
 default_keytab_name = FILE:/etc/krb5.keytab
 default_realm = DOMB.DOMAIN.TLD
 default_ccache_name = KEYRING:persistent:%{uid}

[domain_realm]
 .domb.domain.tld = DOMB.DOMAIN.TLD
 domb.domain.tld = DOMB.DOMAIN.TLD

**Comment by michael-o** [comment]
I was able to reproduce the issue with just knvo and a modified krb5.conf to another trusted forest. I was able to obtain a TGT for the target forgest from my home forest, but of course since I cannot find any DCs in the target forest, it cannot request a service ticket with my target forest krbtgt.

We have now the following problem here: Although it seems that only two domains or forests are involved and we could potentionally add them to the fake krb5.conf, it might still now work when the KDC wants us to follow cross-realm referrals (RFC 6806) through multiple hops which would us require to add every single hop in in the `[realms}` section.

You your foreign security principal has the entitlement to create computer objects in a foreign realm, right?

**Comment by michael-o** [comment]
I did another test: Set the flag to `true` and what MIT Kerberos did is that it still used the `[realms]` section for my home realm, but used DNS to discover the KDC for the foreign realm.

In your case SASL needs to obtain a krbtgt from the user A realm to the B realm to get a service ticket from B realm for a B KDC. Since it cannot locate a DC in A realm it cannot get the `krbtgt/Brealm@Arealm` ticket.

Based on my test with Kerberos 5 Version 1.20.1 it makes sense to switch the flag. I haven't tested with recent Heimdal. I'd also would like to know other comitters' opinion.


@daniellindgren2020 Did you compile a patched version and did it work for you?

**Comment by daniellindgren2020** [comment]
> Your foreign security principal has the entitlement (delegated permissions) to create computer objects in a foreign realm, right?

Yes, UserA from DomA has been granted permissions to create computer accounts in DomB (trusts DomA).

**Comment by daniellindgren2020** [comment]
> @daniellindgren2020 Did you compile a patched version and did it work for you?

Yes, we compiled msktutil with dns_lookup_kdc set to true in create_fake_krb5_conf and we could successfully create a computer account i DomB with credentials from DomA:

    -- finalize_exec: Authenticated using method 5
    -- LDAPConnection: Connecting to LDAP server: DCB.domb.domain.tld
    SASL/GSS-SPNEGO authentication started
    SASL username: usera@DOMA.DOMAIN.TLD
    SASL SSF: 256
    SASL data security layer installed.
    -- ldap_get_base_dn: Determined default LDAP base: dc=DOMB,dc=DOMAIN,dc=TLD
    -- get_default_ou: Using OU: OU=Specific OU for Linux,dc=DOMB,dc=DOMAIN,dc=TLD
    -- ldap_check_account: Checking that a computer account for hostb$ exists
    -- ldap_create_account: Computer account not found, create one

**Comment by michael-o** [comment]
@dkobras  @mproehl Opinions?

**Comment by michael-o** [comment]
@daniellindgren2020 Please prepare a PR.

**Comment by daniellindgren2020** [comment]
> @daniellindgren2020 Please prepare a PR.

Unfortunately I'm not a developer and not familiar with Github.

There's only one line changed in msktconf.cpp, here's a diff:

    --- msktconf.cpp.org	2022-12-21 13:07:19.128198133 +0100
    +++ msktconf.cpp	2022-12-23 08:57:58.149475367 +0100
    @@ -101,7 +101,7 @@
    
        file << "[libdefaults]\n"
            << " default_realm = " << flags->realm_name << "\n"
    -         << " dns_lookup_kdc = false\n"
    +         << " dns_lookup_kdc = true\n"
            << " udp_preference_limit = 1\n"
            << " default_ccache_name = " << KRB5CCache::defaultName() << "\n";

If you or some other developer could do the PR I would be grateful.

**Comment by michael-o** [comment]
> > @daniellindgren2020 Please prepare a PR.
> 
> Unfortunately I'm not a developer and not familiar with Github.
> 
> There's only one line changed in msktconf.cpp, here's a diff:
> 
> ```
> --- msktconf.cpp.org	2022-12-21 13:07:19.128198133 +0100
> +++ msktconf.cpp	2022-12-23 08:57:58.149475367 +0100
> @@ -101,7 +101,7 @@
> 
>     file << "[libdefaults]\n"
>         << " default_realm = " << flags->realm_name << "\n"
> -         << " dns_lookup_kdc = false\n"
> +         << " dns_lookup_kdc = true\n"
>         << " udp_preference_limit = 1\n"
>         << " default_ccache_name = " << KRB5CCache::defaultName() << "\n";
> ```
> 
> If you or some other developer could do the PR I would be grateful.

No issue, I will prepare one.
