### ISSUE TITLE
Configure dependabot

### ISSUE THREAD

**Issue by mjtrangoni** [msktutil/msktutil#214]
Hi,

Dependabot still seems having [no support for C++](https://github.com/dependabot/dependabot-core/issues/2027) but it would worth for keeping the GitHub Actions up-to-date.

If you agree, I can submit a PR on this.

**Comment by michael-o** [comment]
For GHA, it makes sense.

**Comment by dkobras** [comment]
Agreed. A PR adding this support would be most welcome!
