### ISSUE TITLE
Add possibility to create service keytab without changing the password

### ISSUE THREAD

**Issue by oflebbe** [msktutil/msktutil#57]
I have sevice account which is used from Windows and Unix. Password is change once in a while on Windows. I'd like to create service keytabs for that without changing the password. Unfortunately, it always tries to change the password.

I thought "msktutil create --account-name ...  --use-service-account --keytab ~/cool2.keytab --password ..."
would do the think but it doesnt.

Reported by: michael-o

**Comment by sckobras** [comment]
@mproehl The --dont-change-password feature is already implemented in current master. Can this ticket be closed?

**Comment by michael-o** [comment]
I works for me already on HP-UX.

**Comment by mproehl** [comment]
There is one thing left to do before we can close this: `msktutil create --old-account-password Some_p@ssword --dont-change-password` would be a nice use case too. (Suggested by Michael)

**Comment by mproehl** [comment]
Unfortunately timestamps are always set to the current time by `krb5_kt_add_entry()`. So there is no way to copy the timestamp

**Comment by sckobras** [comment]
@mproehl An exact copy of the timestamp should not be necessary. A more recent timestamp just means we might keep entries for an outdated kvno longer than required. But as long as `timestamp >= password_change_time` holds, we should be fine. There's one corner case to consider, though: If adding new entries for multiple kvnos at once, we need to make sure not to mix up the order of entries, ie. start by cloning entries from oldest to youngest.
