### ISSUE TITLE
Enhancement: Delete and Reset Computer Account

### ISSUE THREAD

**Issue by oflebbe** [msktutil/msktutil#58]
Hi,

I'm trying to integrate msktutil into a client deployment solution (Foreman) where I need to pre-create, reset and delete computer accounts in addition to writing out the keytab on the client.

Currently, I'm using msktutil --precreate on the server to create the computer accounts with a default password, and then msktutil --auto-update in a cron job to write the initial and all following keytabs on the client. This works great, thanks for the good work.

To fully complete this picture, I'd like to propose the addition of two commands:
- Delete a computer from AD
- Reset a computer in AD (i.e. set the default password again)

adcli already has functionality like this (adcli delete-computer and adcli reset-computer), but this tool misses out on other important functionality that I depend on (like the possibility for a different NETBIOS name than the hostname) and also I cannot get it to work in our domain where msktutil works fine.

Would this be something you think would be a good fit for msktutil?

Reported by: wagnerp

**Comment by michael-o** [comment]
In master there is already a command `delete-account` which name seems inconsistent to me. I'd expect just `delete` as in `create` or `update`.

**Comment by mproehl** [comment]
yes, that should be reneamed. And it needs to be implemented...

**Comment by mproehl** [comment]
clarification:

*delete* will delete the ad object and needs --account-name (or --computer-name). It will not remove the keytab or any keytab entries.

 *reset* shall be implemented as an alias for `update --password <hostname>`.  A reset only makes sense for computer accounts, right?

**Comment by michael-o** [comment]
If `reset` is for computer accounts, you don't even need `--password`. You can set the default password.
`delete` makes sense.

**Comment by sckobras** [comment]
@michael-o Indeed. The comment was about how this can be implemented internally, not what the end user actually needs to supply.

**Comment by mproehl** [comment]
Yes, I mean `msktutil reset --computername lx02` will be equivalent to `msktutil update --computername lx02 --password lx02`. 

But without any keytab updates BTW.

**Comment by michael-o** [comment]
It also requires `--user-creds-only` because you have to `kinit` with an admin account first.

**Comment by mproehl** [comment]
Hm, we could set `flags->user_creds_only = true` internally when in delete mode. What do you think?
