### ISSUE TITLE
Kerberos flavor incorrectly detected on FreeBSD

### ISSUE THREAD

**Issue by oflebbe** [msktutil/msktutil#59]
We're using MIT Kerberos 1.13.x from Ports system on FreeBSD 9.x exclusively. Unfortunately, the configure script does not properly detect that and sets Heimdal defines in the generated config.h.

Call is: ./configure --with-krb5-config=/usr/local/bin/krb5-config

To explain the situation in FreeBSD: it contains by default an old Heimdal version (base installation) in /usr. MIT Kerberos is installed via Ports system to /usr/local. So, when autoconf tries to detect something, GCC automatically finds Heimdal header files in /usr and ignores /usr/local altough I have provided the config script of MIT Kerberos.

The detection should be improved here. One could learn from Cyrus SASL which has:
--with-gss_impl={heimdal|mit|cybersafe|seam|auto}
                          choose specific GSSAPI implementation [[auto]]
                          
 We'd recude here to heimdal, mit, and auto.
 
 config.log, config.status, and config.h are available on request.

Reported by: michael-o

**Comment by michael-o** [comment]
I will revalidate this next week and and close accordingly.

**Comment by oflebbe** [comment]
Yep, of course.

**Comment by michael-o** [comment]
Tested on FreeBSD 10/11 with Heimdal from base, MIT Kerberos from ports, and Heimdal from ports.
Note: As soon as either one is installed from ports, Heimdal from base won't be used because `/usr/local` takes always precedence for SASL, OpenLAP, etc.
