### ISSUE TITLE
create principals with short names when calling --service

### ISSUE THREAD

**Issue by oflebbe** [msktutil/msktutil#73]
As discussed on #57: while `msktutil create` adds SPNs for `host/...` principals with qualified and unqualified hostnames,  `msktutil create --service ...` does not. This behavour seems inconsistent and we should change it, especially when the argument of --service has no `/component` part (e.g.: --service nfs). 

If the msktutil command line already specifies the component (e.g. `--service foo/bar` or `--service nfs/FQDN`) then there is no good way to add further forms. But if the command line only specifies the service name (e.g. `--service nfs`) the we should add nfs/shortname and nfs/FQDN. The shortname should be the first component of the FQDN, not the sAMAccountName (thay may differ from the 1st component of FQDN).

This makes no sense with --use-service-accounts because service account do not have a dnshostname attribute. So we should only add this new funcionality when operating on machine accounts.

Reported by: mproehl

**Comment by dkobras** [comment]
Closing in favour of #153, which seems to be a duplicate.
