### ISSUE TITLE
Confusing verbose message for user principal name

### ISSUE THREAD

**Issue by oflebbe** [msktutil/msktutil#74]
I see the following verbose output:

~~~
 -- ldap_check_account:   Found User Principal: nexus-dwadmin
 ...
  -- add_principal_keytab: Adding principal to keytab: nexus-dwadmin
~~~

this is rather confusing because this is a sAMAccountName and not a UPN. They are supposed to be email-style logins.

There are at least two of these spots:

~~~
            std::string upn = ldap->get_one_val(mesg, "userPrincipalName");
            if (!upn.empty()) {
                size_t pos = upn.find('@');
                if (pos != std::string::npos) {
                    upn.erase(pos);
                }
                VERBOSE("  Found User Principal: %s", upn.c_str());
                /* update userPrincipalName for salt generation */
                flags->userPrincipalName = upn.c_str();
~~~

and

~~~
void add_principal_keytab(const std::string &principal, msktutil_flags *flags)
{
    VERBOSE("Adding principal to keytab: %s", principal.c_str());
    KRB5Keytab keytab(flags->keytab_writename);

    std::string principal_string = "";

    if (principal.find("@") != std::string::npos) {
        principal_string = sform("%s", principal.c_str());
    } else {
        principal_string = sform("%s@%s",
                                 principal.c_str(),
                                 flags->realm_name.c_str());
~~~

There seems to be an inconsistency in the code as well as terminology.

I wouldn't mind to try a patch, but first I'd like to understand the current situation.

Reported by: michael-o

**Comment by sckobras** [comment]
A principal without a realm component is assumed to be part of the default realm. I'd say the code is ok here, but I wouldn't mind moving the debug output so the principal is always printed including its realm.

**Comment by michael-o** [comment]
Just checked the code again. Unfortunately, in several spots `samAccountName` and `userPrincipalName` are mixed. This makes the code harder to read and confuses the user when verbose flag is on.
