### ISSUE TITLE
Improve AD SRV lookups

### ISSUE THREAD

**Issue by sckobras** [msktutil/msktutil#84]
The way we look up domain controllers from DNS SRV records isn't strictly correct: According to [Microsoft's documentation](https://technet.microsoft.com/en-us/library/cc961719.aspx), `_ldap._tcp.example.com` just gets us some servers that offer an LDAP service, but not necessarily domain controllers. We should use `_ldap._tcp.dc._msdcs.example.com`. (In practice, I have yet to come across a site where both queries return different results.)

**Comment by oflebbe** [comment]
Maybe a site with AD LDS servers ?

**Comment by michael-o** [comment]
I haven't seen anyhting different either in our forests which are, according to our staff, the largest of the planet.

**Comment by sckobras** [comment]
Hence I consider it more of an enhancement than a real bug. Still, it's an easy change to do the right thing, see PR #86.
