### ISSUE TITLE
Failure to write keytab entries for more than one principal

### ISSUE THREAD

**Issue by sckobras** [msktutil/msktutil#85]
Keytab update fails with current master HEAD as soon as the entries for the second principal (usually the sAMAccountName in uppercase) should be written:

<pre>
 -- set_password: Successfully set password
 -- remove_keytab_entries: Trying to remove entries for testaccount$ from keytab
 -- execute: Updating all entries for computer account in testaccount$ in the keytab WRFILE:/etc/krb5.keytab
 -- update_keytab: Updating all entries for testaccount$
 -- add_principal_keytab: Adding principal to keytab: testaccount$
 -- add_principal_keytab: Removing entries with kvno < 0
 -- get_salt: Using salt of DOMAINhosttestaccount.domain
 -- add_principal_keytab:   Adding entry of enctype 0x17
 -- get_salt: Using salt of DOMAINhosttestaccount.domain
 -- add_principal_keytab:   Adding entry of enctype 0x11
 -- get_salt: Using salt of DOMAINhosttestaccount.domain
 -- add_principal_keytab:   Adding entry of enctype 0x12
 -- add_principal_keytab: Adding principal to keytab: TESTACCOUNT$
 -- add_principal_keytab: Removing entries with kvno <  #0
 -- get_salt: Using salt of DOMAINhosttestaccount.domain
 -- add_principal_keytab:   Adding entry of enctype 0x17
Error: krb5_kt_add_entry failed failed (Error writing to key table)
</pre>

This might be a regression introduced in b23c489eebfbebc00b77efdf36a7d08b2956aa9a: Previously, in `add_principal_keytab()`, `cursor` was scoped within the `try`/`catch` block, whereas now its scope extends to the end of the function. However, `libkrb5` won't allow keytab modifications as long as a keytab iterator is still active, so the subsequent calls to `keytab.addEntry()`/`keytab.removeEntry()` fail with `KRB5_KT_IOERR` (aka "Error writing to key table").

I'm currently having a patch tested to check whether to this analysis is correct.

**Comment by oflebbe** [comment]
Hi @sckobras I see this error now as well. Could you please share your patch?

**Comment by sckobras** [comment]
@oflebbe From the feedback I received, the minimal patch (which just re-added a `{ ... }` block where the `try`/`catch` used to be) apparently didn't fix the issue completely, but I haven't been able to have a look at it myself, yet. I'm working on a more thorough re-write of this section anyway, though, that should resolve this issue as well. It's still WIP, but 've pushed the current state to [the sc_prune_keytab_rewrite branch in my fork](https://github.com/sckobras/msktutil/tree/sc_prune_keytab_rewrite) now, but beware: It compiles, but other than that, it's still completely untested.
