### ISSUE TITLE
distinction between create and update

### ISSUE THREAD

**Issue by mproehl** [msktutil/msktutil#91]
We had some discussion about the distinction between `create` and `update` mode in #57.

Basically, these mode do the same. According to the man page `create` is equivalent to `update --service host`

We could change this behaviour:
-  let `msktutil create` fail if the account already exists
-  let `msktutil update` fail if the account does not exist

Opinions?

**Comment by dkobras** [comment]
Might there be legitimate use cases out there where users will always just specify `update --service host`, and expect the account to be created unless it's already there? We'd break these installations if we distinguished between `create` and `update` as suggested. Other than that, the change looks reasonable to me. However, if we're about to overhaul the various modes, I'd vote to include `flush` and `cleanup` into this process as well. The distinction between both is far from intuitive, and they can probably be folded into a single mode with different filter options.

**Comment by oflebbe** [comment]
Breaking the compatibility i.e. current uses of msktutil seems not wise to me.

On a side note: Using msktutil from an automation tool might be unnecessary complicated if we first have to know whether there is already an account created before and we only have to update credentials or not and we have to create an account first.

I would prefer to have an opt-in to a different behaviour like

`msktutil create --fail-if-already-exists `
or
`msktutil update --fail-if-not-exists-before`

If you thing this argument is bogus, please disregard.

**Comment by mproehl** [comment]
I agree with Olaf: this change would break compatibility and we should not do that. I'm closing this issue.
