### ISSUE TITLE
duplicate entries when using service account 

### ISSUE THREAD

**Issue by mproehl** [msktutil/msktutil#92]
When a service account has a sAMAccountName and a userPrincipalName attribute with the same short name (i.e.: sAMAccountName=MaxM and userPrincipalName=MaxM@ads.example.com) then two identical keytab entries are created.

Example:
```
rm /tmp/maxm.keytab                                                             
msktutil create --use-service-account --account-name MaxM --uer-creds-only --keytab /tmp/maxm.keytab --enctypes 0x10
root@lx02:~# klist -keKt /tmp/maxm.keytab
Keytab name: FILE:/tmp/maxm.keytab
KVNO Timestamp           Principal
---- ------------------- ------------------------------------------------------              
  13 08/12/2017 08:13:03 MaxM@ADS.EXAMPLE.COM (aes256-cts-hmac-sha1-96)  (0x8bedff2f3bb66662931ebe7812b86a8151aa2b8c356c411974e4dfcb73ffde7)
  13 08/12/2017 08:13:03 MaxM@ADS.EXAMPLE.COM (aes256-cts-hmac-sha1-96)  (0x8bedff2f3bb66662931ebe7812b86a8151aa2b8c356c411974e4dfcb73ffde7)
```

**Comment by dkobras** [comment]
@mproehl Just to clarify: Is this a new issue caused by the recent updates to master, or did the old code behave this way as well?

**Comment by michael-o** [comment]
I can confirm that. Same issue here.

**Comment by mproehl** [comment]
@dkobras this bug exists since 5b07b86f68749f4a62da6279d3058557267c6b9a

**Comment by mproehl** [comment]
maybe this is interesting...
A `--verbose` run with e170f21 removes the doublette:
```...
 -- update_keytab: Updating all entries for MaxM                                      
 -- add_principal_keytab: Adding principal to keytab: MaxM                            
 -- add_principal_keytab: Removing entries with kvno < 0                              
 -- get_salt: Using salt of ADS.EXAMPLE.COMMaxM                                       
 -- add_principal_keytab:   Adding entry of enctype 0x12                              
 -- add_principal_keytab: Adding principal to keytab: MaxM                            
 -- add_principal_keytab: Removing entries with kvno < 0
 -- add_principal_keytab: Deleting MaxM@ADS.EXAMPLE.COM kvno=57, enctype=18
```

**Comment by dkobras** [comment]
@mproehl Thanks, got it now. Here's what's going on: When `sAMAccountName` and `userPrincipalName` match the same principal, in `update_keytab()` we've always added two entries (per enctype) to the keytab. However, the old pruning logic in `add_principal_keytab()` would remove the first entry when it wrote the second one. That's the `cursor.kvno() == flags->kvno` case hidden in the following checks
<pre>
        if (curr_principal == principal_string &&
            (cursor.kvno() >= flags->kvno ||
                cursor.kvno() < earliest_kvno_to_keep)) {
(...)
</pre>

I missed this case when I rewrote the logic to use timestamps instead of kvnos to sort entries. So we could just go ahead and add an explicit check for duplicates back to `prune_keytab()`, but removing a just-added entry as part of a standard use case feels strange to me. Should we try to avoid the duplication at a higher level (ie. `update_keytab()`) already? What do you think?

**Comment by dkobras** [comment]
@mproehl Can you have a look whether PR #102 fixes things for you? If we want to stick with the remove/add scheme, pushing it into `addEntry()` seems to be the best place.

**Comment by mproehl** [comment]
PR #102  fixex this issue. Thanks Daniel!

**Comment by michael-o** [comment]
I do not consider this to be fixed:

My iUPN is `osipovmi@AD001.SIEMENS.NET` whereas my explicit UPN (enterprise principal) is `michael.osipov@siemens.com`. Look what happens with 6c768e3d6a6cbf90b6f6333a15809e269ba8262f:

     ./msktutil update --use-service-account --dont-change-password --keytab osipovmi.keytab --verbose --account-name osipovmi
     -- execute: Skipping creation of new password
     -- get_dc_host: Attempting to find Domain Controller to use via DNS SRV record in domain AD001.SIEMENS.NET for procotol tcp
     -- validate: Found DC: dc.ad001.siemens.net. Checking availability...
     -- get_dc_host: Found preferred Domain Controller: dc.ad001.siemens.net
     -- create_fake_krb5_conf: Created a fake krb5.conf file: /tmp/.msktkrb5.conf-OLokmK
     -- destroy_g_context: Destroying Kerberos Context
     -- initialize_g_context: Creating Kerberos Context
     -- finalize_exec: SAM Account Name is: osipovmi
     -- try_machine_password: Trying to authenticate for osipovmi with password
     -- create_default_machine_password: Default machine password for osipovmi is osipovmi
     -- try_machine_password: Error: krb5_get_init_creds_keytab failed (Preauthentication failed)
     -- try_machine_password: Authentication with password failed
     -- try_user_creds: Checking if default ticket cache has tickets
     -- finalize_exec: Authenticated using method 5
     -- LDAPConnection: Connecting to LDAP server: dc.ad001.siemens.net
    SASL/GSSAPI authentication started
    SASL username: osipovmi@AD001.SIEMENS.NET
    SASL SSF: 56
    SASL data security layer installed.
     -- ldap_get_base_dn: Determining default LDAP base: dc=AD001,dc=SIEMENS,dc=NET
     -- get_default_ou: Determining default OU: CN=Users,DC=ad001,DC=siemens,DC=net
     -- ldap_check_account: Checking that a service account for osipovmi exists
     -- ldap_check_account: Checking service account - found
     -- ldap_check_account: Found userAccountControl = 0x200
     -- ldap_check_account: Found supportedEncryptionTypes = 28
     -- ldap_check_account: Found User Principal: michael.osipov
     -- ldap_check_account_strings: Inspecting (and updating) service account attributes
     -- ldap_set_supportedEncryptionTypes: No need to change msDs-supportedEncryptionTypes they are 28
     -- ldap_set_userAccountControl_flag: Setting userAccountControl bit at 0x200000 to 0x0
     -- ldap_set_userAccountControl_flag: userAccountControl not changed 0x200
     -- ldap_get_kvno: KVNO is 5
     -- remove_keytab_entries: Trying to remove entries for osipovmi from keytab
     -- add_keytab_entries: Trying to add missing entries for osipovmi to keytab
     -- update_keytab: Updating all entries for osipovmi
     -- add_principal_keytab: Adding principal to keytab: osipovmi
     -- get_salt: Using salt of AD001.SIEMENS.NETmichael.osipov
     -- add_principal_keytab:   Adding entry of enctype 0x17
     -- add_principal_keytab:   Adding entry of enctype 0x11
     -- add_principal_keytab:   Adding entry of enctype 0x12
     -- add_principal_keytab: Adding principal to keytab: michael.osipov
     -- get_salt: Using salt of AD001.SIEMENS.NETmichael.osipov
     -- add_principal_keytab:   Adding entry of enctype 0x17
     -- add_principal_keytab:   Adding entry of enctype 0x11
     -- add_principal_keytab:   Adding entry of enctype 0x12

with written keytab:

    $ klist -k -t osipovmi.keytab     Keytab name: FILE:osipovmi.keytab
    KVNO Timestamp           Principal
    ---- ------------------- ------------------------------------------------------
       5 15.08.2017 10:40:59 osipovmi@AD001.SIEMENS.NET
       5 15.08.2017 10:40:59 osipovmi@AD001.SIEMENS.NET
       5 15.08.2017 10:40:59 osipovmi@AD001.SIEMENS.NET
       5 15.08.2017 10:40:59 michael.osipov@AD001.SIEMENS.NET
       5 15.08.2017 10:40:59 michael.osipov@AD001.SIEMENS.NET
       5 15.08.2017 10:40:59 michael.osipov@AD001.SIEMENS.NET

    $ kinit -k -t osipovmi.keytab michael.osipov@AD001.SIEMENS.NET
    kinit: Client 'michael.osipov@AD001.SIEMENS.NET' not found in Kerberos database while getting initial credentials
    
So, something is still fishy about it.

**Comment by mproehl** [comment]
I think msktutil does not support enterprise principals until now. I'm currently looking at #66 where enterprise names need to be considered as well. (#66 is about salt creation).

But I do not see any duplicates in your klist output. Okay, I see three times the same principal names but I suppose they differ in the enctype, so there is no duplication. Right?

I suggest to close #92 and open and new enhancement issue to support enterprise names

**Comment by michael-o** [comment]
Agreed.

**Comment by sckobras** [comment]
@michael-o What about `kinit -k -t osipovmi.keytab -E michael.osipov@AD001.SIEMENS.NET`? If the UPN entries in the keytab work fine, I agree with @mproehl that this should be treated as a separate issue. According to the debug output, the three entries refer to enctypes `0x11`, `0x12`, and `0x17`, so the duplicates indeed seem to be gone.

**Comment by michael-o** [comment]
@sckobras 

    $ kinit -k -t osipovmi.keytab michael.osipov@AD001.SIEMENS.NET
    kinit: Client 'michael.osipov@AD001.SIEMENS.NET' not found in Kerberos database while getting initial credentials

Yes, those three entries are Arcfour, AES128 and AES256.
