### ISSUE TITLE
Commit 20adbc14fccaab634e2b1273cf0c3a7fffdf536b does not compile with several compilers

### ISSUE THREAD

**Issue by michael-o** [msktutil/msktutil#93]
Tested on `10.3-STABLE FreeBSD 10.3-STABLE #6 r321414: Mon Jul 24 10:37:14 CEST 2017`

    $ cc --version
    FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
    Target: i386-unknown-freebsd10.3
    Thread model: posix
        $ gmake
    Compiling krb5wrap.cpp
    c++ -I.  -I/usr/local/include -g -O2 -Wall -Wextra -Wno-write-strings -c krb5wrap.cpp -o krb5wrap.o
    In file included from krb5wrap.cpp:31:
    In file included from ./msktutil.h:349:
    ./msktname.h:77:37: error: expected ')'
        DnsSrvHost(struct dns_srv dnssrv& const)
                                        ^
    ./msktname.h:77:15: note: to match this '('
        DnsSrvHost(struct dns_srv dnssrv& const)
                  ^
    1 error generated.
    gmake: *** [Makefile:34: krb5wrap.o] Fehler 1
    
    $ gcc --version
    gcc (FreeBSD Ports Collection) 5.4.0
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    $ gmake
    Compiling krb5wrap.cpp
    g++ -I.  -I/usr/local/include -g -O2 -Wall -Wextra -Wno-write-strings -c krb5wrap.cpp -o krb5wrap.o
    In file included from msktutil.h:349:0,
                     from krb5wrap.cpp:31:
    msktname.h:77:37: error: expected ',' or '...' before '&' token
         DnsSrvHost(struct dns_srv dnssrv& const)
                                         ^
    gmake: *** [Makefile:34: krb5wrap.o] Fehler 1
    
    $ clang39 --version
    clang version 3.9.1 (tags/RELEASE_391/final)
    Target: i386-unknown-freebsd10.3
    Thread model: posix
    InstalledDir: /usr/local/llvm39/bin
    
    l$ gmake
    Compiling krb5wrap.cpp
    clang++39 -I.  -I/usr/local/include -g -O2 -Wall -Wextra -Wno-write-strings -c krb5wrap.cpp -o krb5wrap.o
    In file included from krb5wrap.cpp:31:
    In file included from ./msktutil.h:349:
    ./msktname.h:77:37: error: expected ')'
        DnsSrvHost(struct dns_srv dnssrv& const)
                                        ^
    ./msktname.h:77:15: note: to match this '('
        DnsSrvHost(struct dns_srv dnssrv& const)
                  ^
    1 error generated.
    gmake: *** [Makefile:34: krb5wrap.o] Fehler 1
    
    $ clang40 --version
    clang version 4.0.1 (tags/RELEASE_401/final)
    Target: i386-unknown-freebsd10.3
    Thread model: posix
    InstalledDir: /usr/local/llvm40/bin
    
    $ gmake
    Compiling krb5wrap.cpp
    clang++40 -I.  -I/usr/local/include -g -O2 -Wall -Wextra -Wno-write-strings -c krb5wrap.cpp -o krb5wrap.o
    In file included from krb5wrap.cpp:31:
    In file included from ./msktutil.h:349:
    ./msktname.h:77:37: error: expected ')'
        DnsSrvHost(struct dns_srv dnssrv& const)
                                        ^
    ./msktname.h:77:15: note: to match this '('
        DnsSrvHost(struct dns_srv dnssrv& const)
                  ^
    1 error generated.
    gmake: *** [Makefile:34: krb5wrap.o] Fehler 1

**Comment by michael-o** [comment]
Another platform:
    $ uname -a
    HP-UX blnn724x B.11.31 U ia64 HP-UX
    
    $ aCC --version
    aCC: HP C/aC++ B3910B A.06.28.03 [Dec 13 2016]
    
    l$ make
    Compiling krb5wrap.cpp
            aCC -I. -I/usr/local/include  -I/opt/krb5-1.13.1/include -g  -c krb5wrap.cpp -o krb5wrap.o
    "msktname.h", line 77: error #2018: expected a ")"
          DnsSrvHost(struct dns_srv dnssrv& const)
                                          ^
    
    1 error detected in the compilation of "krb5wrap.cpp".
    *** Fehlerrückkehrcode 2
    
    Stopp.

**Comment by dkobras** [comment]
@michael-o Argh, sorry. All my test systems run without `libudns` (obviously). Not sure how I came up with this strange declaration in the first place, but PR #96 should fix it.
