### ISSUE TITLE
Fix warning about unused return value of read()

### ISSUE THREAD

**Issue by oflebbe** [msktutil/msktutil#98]
On ubuntu xenial one gets this error
`g++ -I. -I/usr/include/et  -isystem /usr/include/mit-krb5 -g -O2 -Wall -Wextra -Wno-write-strings -c msktpass.cpp -o msktpass.o
msktpass.cpp: In function ‘int generate_new_password(msktutil_flags*)’:
msktpass.cpp:79:35: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
                 read(fd, &curr, 1);
                                   ^
`

**Comment by dkobras** [comment]
Now this looks nasty. If an attacker were in a position to cause read() to return EINTR (eg. by repeatedly sending a signal at the right time), the entropy of the generated password would be lowered significantly. I ran a quick test on a current Linux system, and wasn't able to win the race, though, but we should err on the safe side and just assume this might be possible on some systems. (Admittedly, sending signals to processes that will usually run as root already requires a privileged position, but might still be used to circumvent restricted capabilities.)
